# Generated by Django 4.1.1 on 2023-06-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndivoapp', '0003_filesadmin_delete_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=1000, upload_to='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='FilesAdmin',
        ),
    ]
